"""add_car_wash_tables

Revision ID: 0aa521cbd314
Revises: a57b582506ad
Create Date: 2026-08-05 22:34:43.883412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa521cbd314'
down_revision: Union[str, Sequence[str], None] = 'a57b582506ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_wash_addons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_wash_addons_service_id'), 'car_wash_addons', ['service_id'], unique=False)
    op.create_index(op.f('ix_car_wash_addons_station_id'), 'car_wash_addons', ['station_id'], unique=False)
    op.create_table('car_wash_order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('addon_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_wash_order_items_addon_id'), 'car_wash_order_items', ['addon_id'], unique=False)
    op.create_index(op.f('ix_car_wash_order_items_order_id'), 'car_wash_order_items', ['order_id'], unique=False)
    op.create_table('car_wash_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('slot_start', sa.DateTime(), nullable=True),
    sa.Column('staff_id', sa.String(length=36), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_wash_orders_service_id'), 'car_wash_orders', ['service_id'], unique=False)
    op.create_index(op.f('ix_car_wash_orders_station_id'), 'car_wash_orders', ['station_id'], unique=False)
    op.create_index(op.f('ix_car_wash_orders_user_id'), 'car_wash_orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_car_wash_orders_vehicle_id'), 'car_wash_orders', ['vehicle_id'], unique=False)
    op.create_table('car_wash_qr_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_wash_qr_payments_nonce'), 'car_wash_qr_payments', ['nonce'], unique=True)
    op.create_index(op.f('ix_car_wash_qr_payments_order_id'), 'car_wash_qr_payments', ['order_id'], unique=False)
    op.create_table('car_wash_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_wash_services_station_id'), 'car_wash_services', ['station_id'], unique=False)
    op.create_table('car_wash_stations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=36), nullable=True),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('opens_at', sa.String(length=20), nullable=True),
    sa.Column('closes_at', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_wash_stations_owner'), 'car_wash_stations', ['owner'], unique=False)
    op.create_index(op.f('ix_car_wash_stations_slug'), 'car_wash_stations', ['slug'], unique=False)
    op.create_table('car_wash_status_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_wash_status_events_order_id'), 'car_wash_status_events', ['order_id'], unique=False)
    op.create_table('car_wash_support_tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('station_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True),
    sa.Column('refund_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_wash_support_tickets_order_id'), 'car_wash_support_tickets', ['order_id'], unique=False)
    op.create_index(op.f('ix_car_wash_support_tickets_station_id'), 'car_wash_support_tickets', ['station_id'], unique=False)
    op.create_index(op.f('ix_car_wash_support_tickets_user_id'), 'car_wash_support_tickets', ['user_id'], unique=False)
    op.create_table('car_wash_vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_wash_vehicles_plate'), 'car_wash_vehicles', ['plate'], unique=False)
    op.create_index(op.f('ix_car_wash_vehicles_user_id'), 'car_wash_vehicles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_wash_vehicles_user_id'), table_name='car_wash_vehicles')
    op.drop_index(op.f('ix_car_wash_vehicles_plate'), table_name='car_wash_vehicles')
    op.drop_table('car_wash_vehicles')
    op.drop_index(op.f('ix_car_wash_support_tickets_user_id'), table_name='car_wash_support_tickets')
    op.drop_index(op.f('ix_car_wash_support_tickets_station_id'), table_name='car_wash_support_tickets')
    op.drop_index(op.f('ix_car_wash_support_tickets_order_id'), table_name='car_wash_support_tickets')
    op.drop_table('car_wash_support_tickets')
    op.drop_index(op.f('ix_car_wash_status_events_order_id'), table_name='car_wash_status_events')
    op.drop_table('car_wash_status_events')
    op.drop_index(op.f('ix_car_wash_stations_slug'), table_name='car_wash_stations')
    op.drop_index(op.f('ix_car_wash_stations_owner'), table_name='car_wash_stations')
    op.drop_table('car_wash_stations')
    op.drop_index(op.f('ix_car_wash_services_station_id'), table_name='car_wash_services')
    op.drop_table('car_wash_services')
    op.drop_index(op.f('ix_car_wash_qr_payments_order_id'), table_name='car_wash_qr_payments')
    op.drop_index(op.f('ix_car_wash_qr_payments_nonce'), table_name='car_wash_qr_payments')
    op.drop_table('car_wash_qr_payments')
    op.drop_index(op.f('ix_car_wash_orders_vehicle_id'), table_name='car_wash_orders')
    op.drop_index(op.f('ix_car_wash_orders_user_id'), table_name='car_wash_orders')
    op.drop_index(op.f('ix_car_wash_orders_station_id'), table_name='car_wash_orders')
    op.drop_index(op.f('ix_car_wash_orders_service_id'), table_name='car_wash_orders')
    op.drop_table('car_wash_orders')
    op.drop_index(op.f('ix_car_wash_order_items_order_id'), table_name='car_wash_order_items')
    op.drop_index(op.f('ix_car_wash_order_items_addon_id'), table_name='car_wash_order_items')
    op.drop_table('car_wash_order_items')
    op.drop_index(op.f('ix_car_wash_addons_station_id'), table_name='car_wash_addons')
    op.drop_index(op.f('ix_car_wash_addons_service_id'), table_name='car_wash_addons')
    op.drop_table('car_wash_addons')
    # ### end Alembic commands ###
