"""add feedback table

Revision ID: 0cbb111b9f98
Revises: 99ca4f03e31f
Create Date: 2026-07-07 21:59:01.824342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbb111b9f98'
down_revision: Union[str, Sequence[str], None] = '99ca4f03e31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_by', sa.String(length=36), nullable=True),
    sa.Column('submitted_by_role', sa.String(length=50), nullable=True),
    sa.Column('tenant', sa.String(length=36), nullable=True),
    sa.Column('estate', sa.String(length=36), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.String(length=36), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_estate'), 'feedback', ['estate'], unique=False)
    op.create_index(op.f('ix_feedback_status'), 'feedback', ['status'], unique=False)
    op.create_index(op.f('ix_feedback_submitted_by'), 'feedback', ['submitted_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_submitted_by'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_status'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_estate'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
