"""fix legacy schema drift

Revision ID: 0ec0003bdb60
Revises: d1b04de86621
Create Date: 2026-07-01 01:20:46.490218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ec0003bdb60'
down_revision: Union[str, Sequence[str], None] = 'd1b04de86621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'salary_expectation',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='salary_expectation::double precision')
    op.alter_column('candidates', 'offered_salary',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='offered_salary::double precision')
    op.alter_column('candidates', 'halo_score',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='halo_score::double precision')
    op.alter_column('candidates', 'skills_score',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='skills_score::double precision')
    op.alter_column('candidates', 'culture_fit_score',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='culture_fit_score::double precision')
    op.alter_column('tenant_telegram_sessions', 'state',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tenant_telegram_sessions', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('tenant_telegram_sessions', 'otp_phone')
    op.drop_column('tenant_telegram_sessions', 'otp')
    op.drop_column('tenant_telegram_sessions', 'otp_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_telegram_sessions', sa.Column('otp_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tenant_telegram_sessions', sa.Column('otp', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('tenant_telegram_sessions', sa.Column('otp_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('tenant_telegram_sessions', 'context',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tenant_telegram_sessions', 'state',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('candidates', 'culture_fit_score',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('candidates', 'skills_score',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('candidates', 'halo_score',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('candidates', 'offered_salary',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('candidates', 'salary_expectation',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
