"""add level1 pipeline fields to deals, model10 entries table

Revision ID: 29dbdbb1722a
Revises: 194ff0c20d27
Create Date: 2026-07-04 22:26:22.977070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29dbdbb1722a'
down_revision: Union[str, Sequence[str], None] = '194ff0c20d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model10_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model10_entries_owner_id'), 'model10_entries', ['owner_id'], unique=False)
    op.add_column('deals', sa.Column('pipeline', sa.String(length=20), nullable=False, server_default='sales'))
    op.add_column('deals', sa.Column('nps', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('ltv', sa.Numeric(precision=12, scale=2, asdecimal=False), nullable=True))
    op.alter_column('deals', 'pipeline', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'ltv')
    op.drop_column('deals', 'nps')
    op.drop_column('deals', 'pipeline')
    op.drop_index(op.f('ix_model10_entries_owner_id'), table_name='model10_entries')
    op.drop_table('model10_entries')
    # ### end Alembic commands ###
