"""add lead pages and leads tables

Revision ID: 35abc03e4e2e
Revises: 29dbdbb1722a
Create Date: 2026-07-04 22:32:31.210842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35abc03e4e2e'
down_revision: Union[str, Sequence[str], None] = '29dbdbb1722a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('headline', sa.String(length=120), nullable=False),
    sa.Column('subheadline', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta_text', sa.String(length=60), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('deliverable_ai_prompt', sa.Text(), nullable=True),
    sa.Column('thank_you_message', sa.String(length=255), nullable=False),
    sa.Column('pixel_meta', sa.String(length=50), nullable=True),
    sa.Column('pixel_google', sa.String(length=50), nullable=True),
    sa.Column('pixel_custom_html', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('submissions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_pages_owner_id'), 'lead_pages', ['owner_id'], unique=False)
    op.create_index(op.f('ix_lead_pages_slug'), 'lead_pages', ['slug'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('lead_page_id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('utm', sa.JSON(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('promoted_deal_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_lead_page_id'), 'leads', ['lead_page_id'], unique=False)
    op.create_index(op.f('ix_leads_owner_id'), 'leads', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_owner_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_page_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_lead_pages_slug'), table_name='lead_pages')
    op.drop_index(op.f('ix_lead_pages_owner_id'), table_name='lead_pages')
    op.drop_table('lead_pages')
    # ### end Alembic commands ###
