"""add lawyer_id and lawyer_signed_at to tenancy_agreements

Revision ID: 4913b9274a3d
Revises: ac2c962824e0
Create Date: 2026-08-15 15:20:29.476922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4913b9274a3d'
down_revision: Union[str, Sequence[str], None] = 'ac2c962824e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenancy_agreements', sa.Column('lawyer_id', sa.String(length=36), nullable=True))
    op.add_column('tenancy_agreements', sa.Column('lawyer_signed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenancy_agreements', 'lawyer_signed_at')
    op.drop_column('tenancy_agreements', 'lawyer_id')
    # ### end Alembic commands ###
