"""add head_office threads and messages

Revision ID: 5f5b3dfd257c
Revises: d597ef54b752
Create Date: 2026-07-13 22:37:23.042168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5b3dfd257c'
down_revision: Union[str, Sequence[str], None] = 'd597ef54b752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create head_office tables. Idempotent — startup create_all may have already
    made them, so skip any that already exist."""
    existing = set(sa.inspect(op.get_bind()).get_table_names())
    if 'head_office_messages' not in existing:
        op.create_table('head_office_messages',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('thread_id', sa.String(length=36), nullable=False),
        sa.Column('owner_id', sa.String(length=36), nullable=False),
        sa.Column('role', sa.String(length=10), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_head_office_messages_owner_id'), 'head_office_messages', ['owner_id'], unique=False)
        op.create_index(op.f('ix_head_office_messages_thread_id'), 'head_office_messages', ['thread_id'], unique=False)
    if 'head_office_threads' not in existing:
        op.create_table('head_office_threads',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('owner_id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_head_office_threads_owner_id'), 'head_office_threads', ['owner_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_head_office_threads_owner_id'), table_name='head_office_threads')
    op.drop_table('head_office_threads')
    op.drop_index(op.f('ix_head_office_messages_thread_id'), table_name='head_office_messages')
    op.drop_index(op.f('ix_head_office_messages_owner_id'), table_name='head_office_messages')
    op.drop_table('head_office_messages')
    # ### end Alembic commands ###
