"""remove telegram integration

Revision ID: 61b30d0f3a69
Revises: aa4e1a73a5b4
Create Date: 2026-07-18 16:41:28.085322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61b30d0f3a69'
down_revision: Union[str, Sequence[str], None] = 'aa4e1a73a5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_telegram_sessions_telegram_id'), table_name='tenant_telegram_sessions')
    op.drop_table('tenant_telegram_sessions')
    op.drop_index(op.f('ix_coach_users_telegram_id'), table_name='coach_users')
    op.drop_table('coach_users')
    op.drop_index(op.f('ix_coach_messages_telegram_id'), table_name='coach_messages')
    op.drop_column('coach_messages', 'telegram_id')
    op.drop_index(op.f('ix_tenants_telegram_id'), table_name='tenants')
    op.drop_column('tenants', 'telegram_id')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.add_column('tenants', sa.Column('telegram_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_tenants_telegram_id'), 'tenants', ['telegram_id'], unique=False)
    op.add_column('coach_messages', sa.Column('telegram_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_coach_messages_telegram_id'), 'coach_messages', ['telegram_id'], unique=False)
    op.create_table('coach_users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('telegram_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('current_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_valuation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_revenue', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_profit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('target_valuation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('their_why', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completed_levels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('customers_served', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('has_growth_flywheel', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('has_operating_system', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('coach_users_pkey'))
    )
    op.create_index(op.f('ix_coach_users_telegram_id'), 'coach_users', ['telegram_id'], unique=True)
    op.create_table('tenant_telegram_sessions',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('telegram_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('temp_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_telegram_sessions_pkey'))
    )
    op.create_index(op.f('ix_tenant_telegram_sessions_telegram_id'), 'tenant_telegram_sessions', ['telegram_id'], unique=True)
    # ### end Alembic commands ###
