"""add tenancy_terms to estates

Revision ID: 6652b71d2a90
Revises: 84754f7ec838
Create Date: 2026-08-07 12:44:01.535323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6652b71d2a90'
down_revision: Union[str, Sequence[str], None] = '84754f7ec838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estates', sa.Column('tenancy_terms', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estates', 'tenancy_terms')
    # ### end Alembic commands ###
