"""add cash sweep waterfall fields

Revision ID: 6db44364aeec
Revises: b5edd7f3fc51
Create Date: 2026-07-01 10:03:03.339488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db44364aeec'
down_revision: Union[str, Sequence[str], None] = 'b5edd7f3fc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so the existing row(s) satisfy NOT NULL
    op.add_column('owner_finance_plans', sa.Column('monthly_opex', sa.Float(), nullable=False, server_default='0'))
    op.add_column('owner_finance_plans', sa.Column('operating_reserve_current', sa.Float(), nullable=False, server_default='0'))
    op.add_column('owner_finance_plans', sa.Column('tax_pct', sa.Float(), nullable=False, server_default='0'))
    op.add_column('owner_finance_plans', sa.Column('tax_current', sa.Float(), nullable=False, server_default='0'))
    op.add_column('owner_finance_plans', sa.Column('sweep_current', sa.Float(), nullable=False, server_default='0'))
    op.add_column('owner_finance_plans', sa.Column('sinking_funds', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner_finance_plans', 'sinking_funds')
    op.drop_column('owner_finance_plans', 'sweep_current')
    op.drop_column('owner_finance_plans', 'tax_current')
    op.drop_column('owner_finance_plans', 'tax_pct')
    op.drop_column('owner_finance_plans', 'operating_reserve_current')
    op.drop_column('owner_finance_plans', 'monthly_opex')
    # ### end Alembic commands ###
