"""add company_name, company_phone, logo_url to estates

Revision ID: 7694b14c8a62
Revises: 97cf0f77248c
Create Date: 2026-08-24 12:18:55.049036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7694b14c8a62'
down_revision: Union[str, Sequence[str], None] = '97cf0f77248c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estates', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('estates', sa.Column('company_phone', sa.String(length=100), nullable=True))
    op.add_column('estates', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estates', 'logo_url')
    op.drop_column('estates', 'company_phone')
    op.drop_column('estates', 'company_name')
    # ### end Alembic commands ###
