"""add review status to tenancy_agreements

Revision ID: 83be6e83794d
Revises: f510351170f0
Create Date: 2026-07-26 18:25:05.694204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83be6e83794d'
down_revision: Union[str, Sequence[str], None] = 'f510351170f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (agreements signed before this
    # review workflow existed default to "pending" rather than failing the
    # NOT NULL add on a non-empty table).
    op.add_column('tenancy_agreements', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('tenancy_agreements', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('tenancy_agreements', sa.Column('reviewed_by', sa.String(length=36), nullable=True))
    op.add_column('tenancy_agreements', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.alter_column('tenancy_agreements', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenancy_agreements', 'reviewed_at')
    op.drop_column('tenancy_agreements', 'reviewed_by')
    op.drop_column('tenancy_agreements', 'rejection_reason')
    op.drop_column('tenancy_agreements', 'status')
    # ### end Alembic commands ###
