"""add_phone_otp_and_carwash_extra_fields

Revision ID: 84754f7ec838
Revises: 0aa521cbd314
Create Date: 2026-08-05 23:58:48.030213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84754f7ec838'
down_revision: Union[str, Sequence[str], None] = '0aa521cbd314'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_otps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('pending_name', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_otps_phone'), 'phone_otps', ['phone'], unique=False)
    op.create_index(op.f('ix_phone_otps_request_id'), 'phone_otps', ['request_id'], unique=True)
    op.add_column('car_wash_orders', sa.Column('ref', sa.String(length=20), nullable=True))
    op.add_column('car_wash_orders', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_car_wash_orders_ref'), 'car_wash_orders', ['ref'], unique=False)
    op.add_column('car_wash_vehicles', sa.Column('is_default', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_wash_vehicles', 'is_default')
    op.drop_index(op.f('ix_car_wash_orders_ref'), table_name='car_wash_orders')
    op.drop_column('car_wash_orders', 'paid_at')
    op.drop_column('car_wash_orders', 'ref')
    op.drop_index(op.f('ix_phone_otps_request_id'), table_name='phone_otps')
    op.drop_index(op.f('ix_phone_otps_phone'), table_name='phone_otps')
    op.drop_table('phone_otps')
    # ### end Alembic commands ###
