"""add delete_otps table

Revision ID: 8c9a5cf24df0
Revises: 6652b71d2a90
Create Date: 2026-08-09 23:12:48.322389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c9a5cf24df0'
down_revision: Union[str, Sequence[str], None] = '6652b71d2a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delete_otps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('resource_label', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delete_otps_resource_id'), 'delete_otps', ['resource_id'], unique=False)
    op.create_index(op.f('ix_delete_otps_resource_type'), 'delete_otps', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delete_otps_resource_type'), table_name='delete_otps')
    op.drop_index(op.f('ix_delete_otps_resource_id'), table_name='delete_otps')
    op.drop_table('delete_otps')
    # ### end Alembic commands ###
