"""add rent_increase_start to tenants

Revision ID: 9723d9701b3b
Revises: 0057ec83a17b
Create Date: 2026-07-03 23:05:08.161677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9723d9701b3b'
down_revision: Union[str, Sequence[str], None] = '0057ec83a17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('rent_increase_start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'rent_increase_start')
    # ### end Alembic commands ###
