"""add lawyer_id to estates

Revision ID: 97cf0f77248c
Revises: 4913b9274a3d
Create Date: 2026-08-19 20:20:07.069938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97cf0f77248c'
down_revision: Union[str, Sequence[str], None] = '4913b9274a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estates', sa.Column('lawyer_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_estates_lawyer_id'), 'estates', ['lawyer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estates_lawyer_id'), table_name='estates')
    op.drop_column('estates', 'lawyer_id')
    # ### end Alembic commands ###
