"""add auto_pay_enabled to tenants

Revision ID: 99ca4f03e31f
Revises: cc8795be1e5b
Create Date: 2026-07-05 20:22:59.276681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ca4f03e31f'
down_revision: Union[str, Sequence[str], None] = 'cc8795be1e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('auto_pay_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'auto_pay_enabled')
    # ### end Alembic commands ###
