"""add_agreement_signing_fields

Revision ID: a57b582506ad
Revises: 83be6e83794d
Create Date: 2026-08-05 01:25:51.835812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57b582506ad'
down_revision: Union[str, Sequence[str], None] = '83be6e83794d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenancy_agreements', sa.Column('lawyer_typed_name', sa.String(length=255), nullable=True))
    op.add_column('tenancy_agreements', sa.Column('lawyer_signature_image', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('agreement_signed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('agreement_typed_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('agreement_signature_image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'agreement_signature_image')
    op.drop_column('users', 'agreement_typed_name')
    op.drop_column('users', 'agreement_signed_at')
    op.drop_column('tenancy_agreements', 'lawyer_signature_image')
    op.drop_column('tenancy_agreements', 'lawyer_typed_name')
    # ### end Alembic commands ###
