"""add outstanding period/due date fields to tenants

Revision ID: aa4e1a73a5b4
Revises: 612922b67f34
Create Date: 2026-07-15 23:05:39.350366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4e1a73a5b4'
down_revision: Union[str, Sequence[str], None] = '612922b67f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('outstanding_period_start', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('outstanding_period_end', sa.DateTime(), nullable=True))
    op.add_column('tenants', sa.Column('outstanding_due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'outstanding_due_date')
    op.drop_column('tenants', 'outstanding_period_end')
    op.drop_column('tenants', 'outstanding_period_start')
    # ### end Alembic commands ###
