"""add playbooks table

Revision ID: b5edd7f3fc51
Revises: 0ec0003bdb60
Create Date: 2026-07-01 09:49:01.054322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5edd7f3fc51'
down_revision: Union[str, Sequence[str], None] = '0ec0003bdb60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playbooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('engine', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=255), nullable=True),
    sa.Column('playbook_owner', sa.String(length=255), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbooks_owner_id'), 'playbooks', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playbooks_owner_id'), table_name='playbooks')
    op.drop_table('playbooks')
    # ### end Alembic commands ###
