"""add tenancy agreements

Revision ID: c1a17972e241
Revises: 61b30d0f3a69
Create Date: 2026-07-20 20:47:11.217451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a17972e241'
down_revision: Union[str, Sequence[str], None] = '61b30d0f3a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenancy_agreements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('estate_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('parties', sa.JSON(), nullable=False),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('typed_name', sa.String(length=255), nullable=False),
    sa.Column('signature_image', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenancy_agreements_estate_id'), 'tenancy_agreements', ['estate_id'], unique=False)
    op.create_index(op.f('ix_tenancy_agreements_owner_id'), 'tenancy_agreements', ['owner_id'], unique=False)
    op.create_index(op.f('ix_tenancy_agreements_tenant_id'), 'tenancy_agreements', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenancy_agreements_tenant_id'), table_name='tenancy_agreements')
    op.drop_index(op.f('ix_tenancy_agreements_owner_id'), table_name='tenancy_agreements')
    op.drop_index(op.f('ix_tenancy_agreements_estate_id'), table_name='tenancy_agreements')
    op.drop_table('tenancy_agreements')
    # ### end Alembic commands ###
