"""money columns to numeric(12,2); unique active tenant per unit

Revision ID: ca28c3ddaf06
Revises: 6db44364aeec
Create Date: 2026-07-03 04:17:36.912608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca28c3ddaf06'
down_revision: Union[str, Sequence[str], None] = '6db44364aeec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_deposits', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('billing_items', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    # Drift reconciliation: model declares these NOT NULL; backfill any NULLs
    # left by the pre-Alembic era before tightening.
    #
    # The columns themselves had no ADD COLUMN migration (the baseline assumed
    # they pre-existed). On a database where estates was create_all'd before
    # the columns entered the model they are absent, so the UPDATE/alter below
    # would 500. Add them if missing first so this revision is self-healing.
    _estate_cols = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("estates")}
    if "rent_increase_percent" not in _estate_cols:
        op.add_column("estates", sa.Column("rent_increase_percent", sa.Float(),
                      nullable=False, server_default="26.0"))
    if "rent_increase_cycle_years" not in _estate_cols:
        op.add_column("estates", sa.Column("rent_increase_cycle_years", sa.Integer(),
                      nullable=False, server_default="2"))
    if "rent_increase_start" not in _estate_cols:
        op.add_column("estates", sa.Column("rent_increase_start", sa.DateTime(),
                      nullable=True))
    op.execute("UPDATE estates SET rent_increase_percent = 26.0 WHERE rent_increase_percent IS NULL")
    op.execute("UPDATE estates SET rent_increase_cycle_years = 2 WHERE rent_increase_cycle_years IS NULL")
    op.alter_column('estates', 'rent_increase_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('26.0'))
    op.alter_column('estates', 'rent_increase_cycle_years',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('payments', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('tenants', 'rent_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('tenants', 'base_rent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('tenants', 'service_charge_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('tenants', 'base_service_charge',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('tenants', 'rent_outstanding',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('tenants', 'service_charge_outstanding',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.create_index('uq_tenants_active_unit', 'tenants', ['unit'], unique=True, postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('units', 'monthly_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('units', 'service_charge_monthly',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('units', 'caution_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('units', 'legal_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'growth_engine_marketing_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'growth_engine_operations_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'growth_engine_savings_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'fulfillment_engine_marketing_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'fulfillment_engine_operations_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'fulfillment_engine_savings_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'innovation_engine_marketing_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'innovation_engine_operations_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'innovation_engine_savings_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'total_received',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'total_disbursed',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallets', 'total_earnings',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('wallets', 'total_spent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    op.alter_column('withdrawals', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2, asdecimal=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('withdrawals', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallets', 'total_spent',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallets', 'total_earnings',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallets', 'balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'total_disbursed',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'total_received',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'innovation_engine_savings_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'innovation_engine_operations_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'innovation_engine_marketing_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'fulfillment_engine_savings_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'fulfillment_engine_operations_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'fulfillment_engine_marketing_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'growth_engine_savings_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'growth_engine_operations_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('wallet_accounts', 'growth_engine_marketing_balance',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('units', 'legal_fee',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('units', 'caution_fee',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('units', 'service_charge_monthly',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('units', 'monthly_price',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_index('uq_tenants_active_unit', table_name='tenants', postgresql_where=sa.text('is_active'), sqlite_where=sa.text('is_active'))
    op.alter_column('tenants', 'service_charge_outstanding',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('tenants', 'rent_outstanding',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('tenants', 'base_service_charge',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('tenants', 'service_charge_amount',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('tenants', 'base_rent',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('tenants', 'rent_amount',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('estates', 'rent_increase_cycle_years',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('estates', 'rent_increase_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('26.0'))
    op.alter_column('billing_items', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('bank_deposits', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2, asdecimal=False),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
