"""add ops manager and integrations hub tables

Revision ID: cc8795be1e5b
Revises: 35abc03e4e2e
Create Date: 2026-07-04 22:40:03.176097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8795be1e5b'
down_revision: Union[str, Sequence[str], None] = '35abc03e4e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_integrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('auth_header', sa.String(length=100), nullable=False),
    sa.Column('auth_value_encrypted', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_integrations_owner_id'), 'business_integrations', ['owner_id'], unique=False)
    op.create_table('integration_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('integration_id', sa.String(length=36), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_snapshots_integration_id'), 'integration_snapshots', ['integration_id'], unique=False)
    op.create_table('ops_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_messages_owner_id'), 'ops_messages', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ops_messages_thread_id'), 'ops_messages', ['thread_id'], unique=False)
    op.create_table('ops_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_reports_owner_id'), 'ops_reports', ['owner_id'], unique=False)
    op.create_table('ops_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_threads_owner_id'), 'ops_threads', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ops_threads_owner_id'), table_name='ops_threads')
    op.drop_table('ops_threads')
    op.drop_index(op.f('ix_ops_reports_owner_id'), table_name='ops_reports')
    op.drop_table('ops_reports')
    op.drop_index(op.f('ix_ops_messages_thread_id'), table_name='ops_messages')
    op.drop_index(op.f('ix_ops_messages_owner_id'), table_name='ops_messages')
    op.drop_table('ops_messages')
    op.drop_index(op.f('ix_integration_snapshots_integration_id'), table_name='integration_snapshots')
    op.drop_table('integration_snapshots')
    op.drop_index(op.f('ix_business_integrations_owner_id'), table_name='business_integrations')
    op.drop_table('business_integrations')
    # ### end Alembic commands ###
