"""baseline existing schema

Revision ID: d1b04de86621
Revises: 
Create Date: 2026-07-01 01:17:38.762342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1b04de86621'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Baseline of the existing database — adopt current state. No-op.

    The schema was previously managed by create_all + manual ALTERs; this
    revision marks that state as the alembic baseline. Future schema changes
    are autogenerated and applied via `alembic upgrade head`.
    """
    pass


def downgrade() -> None:
    pass
