"""add registration to tenancy agreements

Revision ID: f510351170f0
Revises: c1a17972e241
Create Date: 2026-07-20 23:48:33.031847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f510351170f0'
down_revision: Union[str, Sequence[str], None] = 'c1a17972e241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenancy_agreements', sa.Column('registration', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenancy_agreements', 'registration')
    # ### end Alembic commands ###
